# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "C:/Users/91629/Desktop/cpu_third/cpu_third.runs/synth_1/multi_cycle_cpu_display.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param chipscope.maxJobs 4
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a200tfbg676-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/91629/Desktop/cpu_third/cpu_third.cache/wt [current_project]
set_property parent.project_path C:/Users/91629/Desktop/cpu_third/cpu_third.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/91629/Desktop/cpu_third/cpu_third.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
add_files -quiet C:/Users/91629/Desktop/cpu_third/cpu_third.srcs/sources_1/imports/multi_cpu/lcd_module.dcp
set_property used_in_implementation false [get_files C:/Users/91629/Desktop/cpu_third/cpu_third.srcs/sources_1/imports/multi_cpu/lcd_module.dcp]
read_verilog -library xil_defaultlib {
  C:/Users/91629/Desktop/cpu_third/cpu_third.srcs/sources_1/imports/7_multi_cycle_cpu/adder.v
  C:/Users/91629/Desktop/cpu_third/cpu_third.srcs/sources_1/imports/7_multi_cycle_cpu/alu.v
  C:/Users/91629/Desktop/cpu_third/cpu_third.srcs/sources_1/imports/7_multi_cycle_cpu/decode.v
  C:/Users/91629/Desktop/cpu_third/cpu_third.srcs/sources_1/imports/7_multi_cycle_cpu/exe.v
  C:/Users/91629/Desktop/cpu_third/cpu_third.srcs/sources_1/imports/7_multi_cycle_cpu/fetch.v
  C:/Users/91629/Desktop/cpu_third/cpu_third.srcs/sources_1/imports/7_multi_cycle_cpu/mem.v
  C:/Users/91629/Desktop/cpu_third/cpu_third.srcs/sources_1/imports/7_multi_cycle_cpu/multi_cycle_cpu.v
  C:/Users/91629/Desktop/cpu_third/cpu_third.srcs/sources_1/imports/7_multi_cycle_cpu/regfile.v
  C:/Users/91629/Desktop/cpu_third/cpu_third.srcs/sources_1/imports/7_multi_cycle_cpu/wb.v
  C:/Users/91629/Desktop/cpu_third/cpu_third.srcs/sources_1/imports/7_multi_cycle_cpu/multi_cycle_cpu_display.v
}
read_ip -quiet C:/Users/91629/Desktop/cpu_third/cpu_third.srcs/sources_1/ip/inst_rom/inst_rom.xci
set_property used_in_implementation false [get_files -all c:/Users/91629/Desktop/cpu_third/cpu_third.gen/sources_1/ip/inst_rom/inst_rom_ooc.xdc]

read_ip -quiet C:/Users/91629/Desktop/cpu_third/cpu_third.srcs/sources_1/ip/data_ram/data_ram.xci
set_property used_in_implementation false [get_files -all c:/Users/91629/Desktop/cpu_third/cpu_third.gen/sources_1/ip/data_ram/data_ram_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/91629/Desktop/cpu_third/cpu_third.srcs/constrs_1/imports/7_multi_cycle_cpu/multi_cycle_cpu.xdc
set_property used_in_implementation false [get_files C:/Users/91629/Desktop/cpu_third/cpu_third.srcs/constrs_1/imports/7_multi_cycle_cpu/multi_cycle_cpu.xdc]

read_xdc C:/Users/91629/Desktop/cpu_third/cpu_third.srcs/constrs_1/imports/inst/inst_rom_ooc.xdc
set_property used_in_implementation false [get_files C:/Users/91629/Desktop/cpu_third/cpu_third.srcs/constrs_1/imports/inst/inst_rom_ooc.xdc]

set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental C:/Users/91629/Desktop/cpu_third/cpu_third.srcs/utils_1/imports/synth_1/multi_cycle_cpu_display.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top multi_cycle_cpu_display -part xc7a200tfbg676-2
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef multi_cycle_cpu_display.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file multi_cycle_cpu_display_utilization_synth.rpt -pb multi_cycle_cpu_display_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
